services:
  apache:
    image: httpd:2.4
    container_name: apache_digest
    ports:
      - "18080:80"
    volumes:
      - ./var/html/:/usr/local/apache2/htdocs/
      - ./var/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./var/.htdigest:/usr/local/apache2/.htdigest
    restart: unless-stopped
